- action:
  - data:
      entity_id: switch.driveway_lights_switch
    service: switch.turn_on
  alias: 'driveway: dusk - on'
  initial_state: true
  condition: []
  id: '1509773067165'
  trigger:
  - event: sunset
    platform: sun
- action:
  - data:
      entity_id: switch.driveway_lights_switch
    service: switch.turn_off
  alias: 'driveway: dawn - off'
  initial_state: true
  condition: []
  id: '1512625505053'
  trigger:
  - event: sunrise
    platform: sun
- action:
  - data:
      entity_id: switch.stairs_light_switch
    service: switch.turn_on
  - data:
      entity_id: switch.kitchen_light_switch
    service: switch.turn_on
  alias: Stairs Light On @ 6:30pm
  initial_state: false
  condition: []
  id: '1514178318541'
  trigger:
  - at: '18:30:00'
    platform: time
- action:
  - data:
      entity_id: switch.stairs_light_switch
    service: switch.turn_off
  alias: Stairs Light off @ 8:30pm
  initial_state: false
  condition: []
  id: '1514178449121'
  trigger:
  - at: '20:30:00'
    platform: time
- action:
  - data:
      brightness: 100
      entity_id: light.rainbow
      rgb_color:
      - 255
      - 100
      - 200
    service: light.turn_on
  alias: Pink Door
  initial_state: true
  condition: []
  id: '1517750201173'
  trigger:
  - entity_id: binary_sensor.bedroom_door_sensor
    from: 'off'
    platform: state
    to: 'on'
- action:
  - service: script.door_flash
  alias: Bedroom Door Flash
  condition: []
  id: '1517981772506'
  trigger:
  - entity_id: binary_sensor.bedroom_door_sensor
    from: 'off'
    platform: state
    to: 'on'
