- action:
  - data:
      entity_id: switch.driveway_lights_switch
    service: switch.turn_on
  alias: 'driveway: dusk - on'
  initial_state: true
  condition: []
  id: '1509773067165'
  trigger:
  - event: sunset
    platform: sun
- action:
  - data:
      entity_id: switch.driveway_lights_switch
    service: switch.turn_off
  alias: 'driveway: dawn - off'
  initial_state: true
  condition: []
  id: '1512625505053'
  trigger:
  - event: sunrise
    platform: sun
- id: '1514178318541'
  alias: Vacation Lights On @ Sunset
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - data:
      entity_id: switch.stairs_light_switch
    service: switch.turn_on
  - data:
      entity_id: switch.kitchen_light_switch
    service: switch.turn_on
  initial_state: false
- id: '1514178449121'
  alias: Vacation Lights Off @ Sunset + 2h
  trigger:
  - event: sunset
    offset: 02:00:00
    platform: sun
  condition: []
  action:
  - data:
      entity_id: switch.stairs_light_switch
    service: switch.turn_off
  - data:
      entity_id: switch.kitchen_light_switch
    service: switch.turn_off
  initial_state: false
- action:
  - data:
      brightness: 100
      entity_id: light.rainbow
      rgb_color:
      - 255
      - 100
      - 200
    service: light.turn_on
  alias: Pink Door
  initial_state: false
  condition: []
  id: '1517750201173'
  trigger:
  - entity_id: binary_sensor.bedroom_door_sensor
    from: 'off'
    platform: state
    to: 'on'
- action:
  - service: script.door_flash
  alias: Bedroom Door Flash
  initial_state: false
  condition:
  - after: '19:00:00'
    before: 01:00:00
    condition: time
  id: '1517981772506'
  trigger:
  - entity_id: binary_sensor.bedroom_door_sensor
    from: 'off'
    platform: state
    to: 'on'
- alias: Stairs Motion On
  id: stairs_motion_on
  trigger:
  - entity_id: binary_sensor.motion_sensor
    platform: state
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: switch.stairs_light_switch
    state: 'off'
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - data:
      entity_id: switch.stairs_light_switch
    service: switch.turn_on
- alias: Stairs Motion Off
  id: stairs_motion_off
  trigger:
  - entity_id: binary_sensor.motion_sensor
    platform: state
    to: 'off'
    for:
      minutes: 1
  condition:
  - condition: state
    entity_id: switch.stairs_light_switch
    state: 'on'
  action:
  - data:
      entity_id: switch.stairs_light_switch
    service: switch.turn_off
