homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 340
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Detroit
  # Customization file
  customize: !include customize.yaml

http:
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

introduction: # Show links to resources in log and frontend
frontend:     # Enables the frontend
updater:      # Checks for available updates
config:       # Enables configuration UI
# discovery:    # Discover some devices automatically
conversation: # Allows you to issue voice commands from the frontend in enabled browsers
history:      # Enables support for tracking state changes over time
logbook:      # View all events in a logbook
map:          # Enables a map showing the location of tracked devices
sun:          # Track the sun

recorder:
  purge_interval: 2
  purge_keep_days: 6

# Weather prediction
sensor:
  - platform: yr

# Text to speech
tts:
  - platform: google

# Z-Wave and Zigbee via HUSBZB-1
zwave:
 usb_path: /dev/ttyUSB0
 debug: false
 
zha:
 usb_path: /dev/ttyUSB1
 database_path: /home/homeassistant/.homeassistant/zigbee.db

ecobee:
 api_key: !secret ecobee_api_key

light:
  - platform: tplink
    name: Rainbow
    host: 192.168.1.242

wemo:

media_player:
  - platform: roku
    timeout: 20

device_tracker:
  - platform: asuswrt
    host: 192.168.1.1
    username: !secret router_username
    password: !secret router_password
    protocol: telnet
    port: 23
    interval_seconds: 60
    consider_home: 360
    new_device_defaults:
      track_new_devices: false
      hide_if_away: true

cloud:
  alexa:
    filter:
      include_entities:
        - light.family_lights_level
        - switch.circle_plug_switch
        - switch.driveway_lights_switch
        - switch.fan_switch
        - switch.kitchen_light_switch
        - switch.stairs_light_switch
        - switch.orange_lamp
      include_domains:
        - light
        - switch

  google_actions:
    filter:
      include_entities:
        - light.family_lights_level
        - switch.circle_plug_switch
        - switch.driveway_lights_switch
        - switch.fan_switch
        - switch.kitchen_light_switch
        - switch.stairs_light_switch
        - switch.orange_lamp
      include_domains:
        - light
        - switch

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
